/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/object-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listObjectTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{calculationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCalculation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Только для авторизованного пользователя. */
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создаёт пользователя и открывает сессию (httpOnly cookie). */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущий пользователь по cookie. 401, если сессии нет. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/object-types/{slug}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Состав полей паспорта объекта зависит от типа объекта. */
        get: operations["getObjectParameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/object-types/{slug}/parameters/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Разбор загруженного Excel/CSV в значения паспорта объекта. */
        post: operations["importObjectParameters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создаёт копию проекта для сравнения сценариев внутри проекта (см. 3.1.3 ТЗ: не менее трёх сценариев). Доступно только владельцу проекта. */
        post: operations["copyProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/solutions/{solutionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Доступно роли admin. */
        put: operations["updateSolution"];
        post?: never;
        delete: operations["deleteSolution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Иерархия отрасль → объект → процесс → тип решения → продукт. */
        get: operations["getTaxonomy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
            organization?: string;
        };
        User: {
            id: string;
            email: string;
            name: string;
            organization?: string;
            /** @enum {string} */
            role: "user" | "admin";
        };
        ParameterField: {
            id: string;
            label: string;
            hint?: string;
            unit?: string;
            /** @description Заголовок группы полей в форме ввода параметров объекта */
            section?: string;
            /** @enum {string} */
            kind: "number" | "text" | "select";
            min?: number;
            max?: number;
            defaultValue?: string;
            options?: {
                value: string;
                label: string;
            }[];
        };
        ImportedParameters: {
            values: {
                [key: string]: string;
            };
            recognized: number;
            skipped?: string[];
        };
        ProjectInput: {
            title: string;
            objectType: string;
            parameters: {
                [key: string]: string;
            };
            processes?: string[];
        };
        ProjectDetail: components["schemas"]["Project"] & {
            objectType: string;
            parameters: {
                [key: string]: string;
            };
            processes?: string[];
            /** @description Минимум три — «как есть», «покупка», «услуга/RaaS». */
            scenarios: components["schemas"]["ScenarioBar"][];
            calculationId?: string;
        };
        TaxonomyNode: {
            id: string;
            label: string;
            /** @enum {string} */
            level: "industry" | "object" | "process" | "solutionType" | "product";
            children?: components["schemas"]["TaxonomyNode"][];
        };
        SensitivityFactor: {
            id: string;
            label: string;
            /** @description Влияние на срок окупаемости, доля от базового значения. */
            impact: number;
            /** @enum {string} */
            direction: "up" | "down";
            low?: string;
            high?: string;
        };
        /** @enum {string} */
        DataConfidence: "confirmed" | "needs-review";
        /** @enum {string} */
        Maturity: "operation" | "piloting" | "rnd";
        ObjectType: {
            slug: string;
            title: string;
            description: string;
            solutionsCount: number;
            solutionsCountLabel?: string;
            paybackRange: string;
            photoCaption: string;
        };
        ScenarioBar: {
            id: string;
            title: string;
            subtitle: string;
            tco: number;
            share: number;
            delta: string;
            detail?: string;
            recommended?: boolean;
        };
        CostLine: {
            title: string;
            amount: number;
            share: number;
            source: string;
            confidence?: components["schemas"]["DataConfidence"];
        };
        CostGroup: {
            id: string;
            title: string;
            amount: number;
            share: number;
            confidence: components["schemas"]["DataConfidence"];
            lines: components["schemas"]["CostLine"][];
        };
        CalculationResult: {
            id: string;
            objectTitle: string;
            meta: string;
            payback: components["schemas"]["Kpi"];
            capex: components["schemas"]["Kpi"];
            roi: components["schemas"]["Kpi"];
            opexSaving: {
                series: number[];
                percent: string;
                meta: string;
            };
            warning: string;
            assumptions: string[];
            scenarios: components["schemas"]["ScenarioBar"][];
            costGroups: components["schemas"]["CostGroup"][];
            totalTco: number;
            /** @description Параметры, ранжированные по влиянию на результат. */
            sensitivity?: components["schemas"]["SensitivityFactor"][];
        };
        Kpi: {
            label: string;
            value: string;
            unit?: string;
            note?: string;
            /** @enum {string} */
            trend?: "up" | "down" | "none";
        };
        Solution: {
            id: string;
            name: string;
            vendor: string;
            useCase: string;
            price: string;
            payload: string;
            speed: string;
            maturity: components["schemas"]["Maturity"];
            confidence: components["schemas"]["DataConfidence"];
            /** @description Название источника характеристик. */
            source?: string;
            /** @description Дата актуальности источника. */
            sourceDate?: string;
            /** @description Типы объектов, для которых решение применимо. */
            objectTypes?: string[];
            /** @description Итоговый балл ранжирования */
            score?: number;
            /** @description Вклад критериев в позицию решения. */
            scoreFactors?: {
                label: string;
                weight: number;
            }[];
        };
        Project: {
            id: string;
            title: string;
            meta: string;
            payback: string;
            status: components["schemas"]["Maturity"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listObjectTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Типы объектов для мастера расчёта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectType"][];
                };
            };
        };
    };
    getCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calculationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результат расчёта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationResult"];
                };
            };
        };
    };
    listSolutions: {
        parameters: {
            query?: {
                /** @description Оставить только решения, применимые к типу объекта. */
                objectType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Каталог решений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Solution"][];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Расчёты пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Требуется вход */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Проект создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Требуется вход */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Сессия открыта */
            201: {
                headers: {
                    /** @description sid=<opaque>; HttpOnly; Path=/; SameSite=Lax */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Пользователь уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Сессия открыта */
            200: {
                headers: {
                    /** @description sid=<opaque>; HttpOnly; Path=/; SameSite=Lax */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Неверная пара логин/пароль */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия закрыта */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Сессии нет */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getObjectParameters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Схема полей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterField"][];
                };
            };
        };
    };
    importObjectParameters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Распознанные значения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportedParameters"];
                };
            };
            /** @description Файл не распознан */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проект с входными параметрами и сценариями */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copyProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Копия создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Требуется вход */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solutionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Solution"];
            };
        };
        responses: {
            /** @description Обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Solution"];
                };
            };
            /** @description Недостаточно прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solutionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTaxonomy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Дерево каталога */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNode"][];
                };
            };
        };
    };
}
